Frutika/Frutika/urls.py
from django.contrib import admin
from django.urls import path
from shop import views


from django.conf import settings
from django.conf.urls.static import static
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('shop.urls')),
    path('user/',include('user.urls')),
    path('cart/',include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Frutika/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'



urlpatterns = [
    

    path('addtocart/<int:pk>/',views.addto_cart,name='addto_cart'),

    path('cartview/',views.cart_view,name='cart_view'),

    path('cartminus/<int:pk>/',views.cart_minus,name='cart_minus'),

    path('cartdelete/<int:pk>/',views.cart_delete,name='cart_delete'),

    path('placeorder/',views.place_order,name='place_order'),

    path('payment_status/<str:pk>/',views.payment_status,name='payment_status'),

    path('yourorders/',views.your_orders,name='your_orders'),
    

] 

Frutika/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'



urlpatterns = [
    

    path('',views.categories,name='categories'),

    path('products/<int:pk>/',views.products,name='products'),

    path('details/<int:pk>/',views.product_details,name='details'),

    path('addcategory/',views.add_category,name='add_category'),

    path('addproducts/',views.add_products,name='add_products'),

    path('addstock/<int:pk>/',views.add_stock,name='add_stock'),

    path('search',views.search,name='search'),

    

] 

Frutika/user/urls.py
from django.contrib import admin
from django.urls import path
from user import views
app_name='user'



urlpatterns = [
    

    path('register/',views.register,name='register'),
    path('signin/',views.signin,name='signin'),
    path('signout/',views.signout,name='signout'),

] 

Frutika/templates/add_category.html
{%extends 'base.html'%}

{%block main_block%}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row" style="height: 2px;">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<div class="container">
    <div class="row mt-2 p-2">
        <div class="col-3"></div>
        <div class="col-6">
            <div>
                <h2 class="text-center fw-bold">Add Categories</h2>
            </div>
            <form action="" method="post" class="border border-2 shadow rounded p-3"  enctype="multipart/form-data">
                {%csrf_token%}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Name of category:</label>
                    <input type="text" class="form-control" name="na" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Category image</label>
                    <input type="file" class="form-control" name="im" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Category description</label>
                    <input type="text" class="form-control" name="de" id="exampleFormControlInput1">
                  </div>
                  <center><button type="submit" class="btn btn-primary">Submit</button></center>


            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>


{%endblock%}

Frutika/templates/add_products.html
{%extends 'base.html'%}

{%block main_block%}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row" style="height: 2px;">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<div class="container">
    <div class="row mt-2 p-2">
        <div class="col-3"></div>
        <div class="col-6">
            <div>
                <h2 class="text-center fw-bold">Add Products</h2>
            </div>
            <form action="" method="post" class="border border-2 shadow rounded p-3"  enctype="multipart/form-data">
                {%csrf_token%}
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Name of product:</label>
                    <input type="text" class="form-control" name="na" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Product image:</label>
                    <input type="file" class="form-control" name="im" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Price:</label>
                    <input type="number" class="form-control" name="pr" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Stock:</label>
                    <input type="number" class="form-control" name="st" id="exampleFormControlInput1">
                  </div>

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Select category:</label>
                    <select name="ca" id="">
                        {%for l in link%}
                        <option value="{{l.name}}">{{l.name}}</option>
                        {%endfor%}
                      </select>
                  </div>
                 

                  <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Product description</label>
                    <input type="text" class="form-control" name="de" id="exampleFormControlInput1">
                  </div>
                  <center><button type="submit" class="btn btn-primary">Submit</button></center>


            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>


{%endblock%}

Frutika/templates/addto_cart.html
{%extends 'base.html'%}
{%block main_block%}


<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Cart</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<!-- cart -->
<div class="cart-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="cart-table-wrap">
                    <table class="cart-table">
                        <thead class="cart-table-head">
                            <tr class="table-head-row">
                                <th class="product-remove">Action</th>
                                <th class="product-image">Product Image</th>
                                <th class="product-name">Product Name</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {%for ca in cart%}
                            <tr class="table-body-row">

                               {% if ca.product.stock > 0 %}
                               <td> <a href="{%url 'cart:addto_cart' ca.product.id%}"><i class="fa fa-plus-circle text-success" aria-hidden="true"></i></a>
                                <a href="{%url 'cart:cart_minus' ca.product.id%}"><i class="fa fa-minus-circle text-warning" aria-hidden="true"></i></a>  
                                  <a href="{%url 'cart:cart_delete' ca.product.id%}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a>  </td>

                               {%else%}
                                  <td> <a href="{%url 'cart:cart_minus' ca.product.id%}"><i class="fa fa-minus-circle text-warning" aria-hidden="true"></i></a>  
                                  <a href="{%url 'cart:cart_delete' ca.product.id%}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></td></a> </td>  
                                 {%endif%}
                                <!-- <td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td> -->
                                <td class="product-image"><img src="{{ca.product.image.url}}" alt=""></td>
                                <td class="product-name">{{ca.product.name}}</td>
                                <td class="product-price">{{ca.product.price}}</td>
                                <td class="product-quantity">{{ca.quantity}}</td>
                               

                                <!-- <td class="product-quantity"><input type="number" placeholder="0"></td> -->
                                <td class="product-total">{{ca.sub_total}}</td>
                            </tr>
                            {%endfor%}
                           
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="total-section">
                    <table class="total-table">
                        <thead class="total-table-head">
                            <tr class="table-total-row">
                                <th>Total</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="total-data">
                                <td><strong>Subtotal: </strong></td>
                                <td>{{total}}</td>
                            </tr>
                           
                        </tbody>
                    </table>
                    <div class="cart-buttons">
                        <a href="{%url 'cart:place_order'%}" class="boxed-btn">Place Order</a>
                        <a href="{%url 'shop:categories'%}" class="boxed-btn black">Continue shopping</a>
                    </div>
                </div>

                <!-- <div class="coupon-section">
                    <h3>Apply Coupon</h3>
                    <div class="coupon-form-wrap">
                        <form action="index.html">
                            <p><input type="text" placeholder="Coupon"></p>
                            <p><input type="submit" value="Apply"></p>
                        </form>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end cart -->


{%endblock%}

Frutika/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Fruitkha</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{%static 'img/favicon.png'%}">
	<!-- google font -->
	<link href="{%static 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700'%}" rel="stylesheet">
	<link href="{%static 'https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap'%}" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{%static 'css/all.min.css'%}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{%static 'css/owl.carousel.css'%}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{%static 'css/magnific-popup.css'%}">
	<!-- animate css -->
	<link rel="stylesheet" href="{%static 'css/animate.css'%}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{%static 'css/meanmenu.min.css'%}">
	<!-- main style -->
	<link rel="stylesheet" href="{%static 'css/main.css'%}">
	<!-- responsive -->
	<link rel="stylesheet" href="{%static 'css/responsive.css'%}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

	

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{%static 'index.html'%}">
								<img src="{%static 'img/logo.png'%}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{%url 'shop:categories'%}">Home</a>
									
								</li>
								<li><a href="{%static 'about.html'%}">About</a></li>
								<li><a href="#">Pages</a>
									
									<ul class="sub-menu">
										{%for l in link%}
										<li><a href="{%url 'shop:products' l.id%}">{{l.name}}</a></li>
										{%endfor%}
									</ul>
									
								</li>

								<a class="mobile-hide search-bar-icon" href="{%url 'shop:search'%}"><i class="fas fa-search"></i></a>

								{%if user.is_authenticated%}
								{%if user.is_superuser%}
								<li><a href="{%url 'shop:add_category'%}">Add Categories</a></li>
								<li><a href="{%url 'shop:add_products'%}">Add Products</a></li>
								{%else%}
								<li>
									<div class="header-icons">
										<a class="shopping-cart" href="{%url 'cart:cart_view'%}"><i class="fas fa-shopping-cart"></i>{{count}}</a>
										
									</div>
								</li>
								{%endif%}

								<li><a href="{%static 'contact.html'%}">Contact</a></li>
								<li><a href="{%url 'cart:your_orders'%}">Your orders</a></li>
								<li><a href="{%url 'user:signout'%}">Logout</a>									
								</li>

								
                        
                                {%else%}
								<li><a href="{%url 'user:register'%}">Register</a>									
								</li>
								<li><a href="{%url 'user:signin'%}">Login</a>									
								</li>

								
								
								{%endif%}
								
							</ul>
						</nav>
						



						<a class="mobile-show search-bar-icon" href="{%url 'shop:search'%}"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
	
	






{%block main_block%}

{%endblock%}


<br>
<br>
<br>

<!-- footer -->
<div class="footer-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="footer-box about-widget">
					<h2 class="widget-title">About us</h2>
					<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box get-in-touch">
					<h2 class="widget-title">Get in Touch</h2>
					<ul>
						<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
						<li>support@fruitkha.com</li>
						<li>+00 111 222 3333</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box pages">
					<h2 class="widget-title">Pages</h2>
					<ul>
						<li><a href="{%static 'index.html'%}">Home</a></li>
						<li><a href="{%static 'about.html'%}">About</a></li>
						<li><a href="{%static 'services.html'%}">Shop</a></li>
						<li><a href="{%static 'news.html'%}">News</a></li>
						<li><a href="{%static 'contact.html'%}">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box subscribe">
					<h2 class="widget-title">Subscribe</h2>
					<p>Subscribe to our mailing list to get the latest updates.</p>
					<form action="{%static 'index.html'%}">
						<input type="email" placeholder="Email">
						<button type="submit"><i class="fas fa-paper-plane"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end footer -->

<!-- copyright -->
<div class="copyright">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-12">
				<p>Copyrights &copy; 2019 - <a href="{%static 'https://imransdesign.com/'%}">Imran Hossain</a>,  All Rights Reserved.</p>
			</div>
			<div class="col-lg-6 text-right col-md-12">
				<div class="social-icons">
					<ul>
						<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
						<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
						<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
						<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end copyright -->

<!-- jquery -->
<script src="{%static 'js/jquery-1.11.3.min.js'%}"></script>
<!-- bootstrap -->
<script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
<!-- count down -->
<script src="{%static 'js/jquery.countdown.js'%}"></script>
<!-- isotope -->
<script src="{%static 'js/jquery.isotope-3.0.6.min.js'%}"></script>
<!-- waypoints -->
<script src="{%static 'js/waypoints.js'%}"></script>
<!-- owl carousel -->
<script src="{%static 'js/owl.carousel.min.js'%}"></script>
<!-- magnific popup -->
<script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
<!-- mean menu -->
<script src="{%static 'js/jquery.meanmenu.min.js'%}"></script>
<!-- sticker js -->
<script src="{%static 'js/sticker.js'%}"></script>
<!-- main js -->
<script src="{%static 'js/main.js'%}"></script>

</body>
</html>

Frutika/templates/categories.html
{%extends 'base.html'%}
{%load static%}
{%block main_block%}

	<!-- hero area -->
    <div class="hero-area hero-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 offset-lg-2 text-center">
                    <div class="hero-text">
                        <div class="hero-text-tablecell">
                            <p class="subtitle">Fresh & Organic</p>
                            <h1>Delicious Seasonal Fruits</h1>
                            <div class="hero-btns">
                                <a href="{%static 'shop.html'%}" class="boxed-btn">Fruit Collection</a>
                                <a href="{%static 'contact.html'%}" class="bordered-btn">Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- hero area end -->


<div class="container w-50 mx-auto mt-5 mb-5">
<h3 class="text-center" style="font-size: 45px;">Our Collections</h3>
<p style="text-align: justify;line-height: 2;font-size: 20px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam, alias doloribus sit aliquid nemo nihil voluptates, accusantium, doloremque hic aliquam veritatis nam itaque. A, ratione numquam unde quibusdam recusandae sit!</p>
</div>

<!-- product section -->
<!-- <div class="product-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="section-title">	
                    <h3><span class="orange-text">Our</span> Products</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, fuga quas itaque eveniet beatae optio.</p>
                </div>
            </div>
        </div> -->

        <div class="row">
            {%for c in cat%}
            <div class="col-lg-4 col-md-6 text-center">
                <div class="single-product-item">
                    <div class="product-image">
                        <a href="{%url 'shop:products' c.id%}"><img src="{{c.image.url}}" alt="" height="300px" width="100%"></a>
                    </div>
                    <h5 style="font-size: x-large;color: darkred;">{{c.name}}</h5>
                    <a href="{%url 'shop:products' c.id%}" class="cart-btn">View</a>
                </div>
            </div>
            {%endfor%}
            
        </div>
    </div>
</div>
<!-- end product section -->

{%endblock%}

Frutika/templates/home.html
{%extends 'base.html'%}
{%block main_block%}
<div class="container-fluid bg-secondary">
    <h1>Welcome to Home Page</h1>
</div>
{%endblock%}

Frutika/templates/payment.html
{%extends 'base.html'%}
{%block main_block%}


<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Payment</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<center>

<form action="{%url 'cart:payment_status' name%}" method="POST">
    <script
       src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_FlS15ifJjCvzOY" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="My Shop"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="{{name}}"
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
    </form>


</center>

{%endblock%}

Frutika/templates/payment_status.html
{%extends 'base.html'%}
{%block main_block%}


<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Payment Success</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->


{%endblock%}

Frutika/templates/pro_details.html
{%extends 'base.html'%}
{%block main_block%}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Product Details</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<div class="single-product mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="single-product-img">
                    <img src="{{p.image.url}}" alt="" height="500px">
                </div>
            </div>
            <div class="col-md-7">
                <div class="single-product-content">
                    <h2 class="fw-bold">{{p.name}}</h2>
                    <p class="single-product-pricing"><span></span>₹ {{p.price}}</p>
                    <p>{{p.desc}}</p>
                    <h4>Stock:{{p.stock}}</h4>

              {%if user.is_superuser%}      
                 {%if p.stock > 0%}
                 <p>Product in stock</p>
                 <a href="{%url 'shop:add_stock' p.id%}" class="cart-btn">Add stock</a>
                 {%else%}
                 <p>Product out of stock</p>
                 <a href="{%url 'shop:add_stock' p.id%}" class="cart-btn">Add stock</a>
                 {%endif%}


                 <!-- if user is normal user -->
             {%else%}  
             <div class="single-product-form">
                <p>Quantity</p>
                <form action="index.html">
                    <input type="number" placeholder="0">
                </form>
            </div>
                   
                {%if p.stock > 0 %}
                <a href="{%url 'cart:addto_cart' p.id %}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                {%else%}
                <p>Out of stock</p>
                {%endif%}


              {%endif%}            

                                        
                    
                   
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

Frutika/templates/products.html
{%extends 'base.html'%}
{%block main_block%}


<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Products</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->

<div class="container">
  <center>  <img src="{{cat.image.url}}" alt="" width="700px" height="400px"></center>
  </div>
  <div class="text-center mt-3"><h1>{{cat.name}}</h1>
    </div>
    <div class="text-center"><p>Slide down for more products</p></div>

<!-- single product -->
 {%for p in pro%}
<div class="single-product mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="single-product-img">
                    <img src="{{p.image.url}}" alt="" height="250px" width="200px">
                </div>
            </div>
            <div class="col-md-7">
                <div class="single-product-content">
                    <h3>{{p.name}}</h3>
                    <p class="single-product-pricing"><span></span>₹ {{p.price}}</p>
                    <div class="single-product-form">
                       
                        <a href="{%url 'shop:details' p.id%}" class="cart-btn">Details</a>
                        <!-- <p><strong>Categories: </strong>Fruit</p> -->
                    </div>
                    <h4>Share:</h4>
                    <ul class="product-share">
                        <li><a href=""><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href=""><i class="fab fa-twitter"></i></a></li>
                        <li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
                        <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{%endfor%}
<!-- end single product -->

{%endblock%}

Frutika/templates/search.html
{%extends 'base.html'%}
{%block main_block%}

{%if products == None%}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                    <h1>Search For:</h1>
                    <div>
                        <form action="{%url 'shop:search'%}" method="post">
                            {%csrf_token%}
                            <div class="mb-3">
                                <input type="text" name="se" class="form-control">
                                <input type="submit" class="btn mt-3">

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- end breadcrumb section -->

<!-- search results -->



{%else%}

<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row" style="height: 2px;">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end breadcrumb section -->
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            
             <h3 class="text-center mt-3">Search results for:<b class="text-info">{{search}}</b></h3>
             {%for p in products%}
             <div class="single-product mt-150 mb-150">
                 <div class="container">
                     <div class="row">
                         <div class="col-md-5">
                             <div class="single-product-img">
                                 <img src="{{p.image.url}}" alt="" height="250px" width="200px">
                             </div>
                         </div>
                         <div class="col-md-7">
                             <div class="single-product-content">
                                 <h3>{{p.name}}</h3>
                                 <p class="single-product-pricing"><span></span>₹ {{p.price}}</p>
                                 <div class="single-product-form">
                                    
                                     <a href="{%url 'shop:details' p.id%}" class="cart-btn">Details</a>
                                     <!-- <p><strong>Categories: </strong>Fruit</p> -->
                                 </div>
                                 <h4>Share:</h4>
                                 <ul class="product-share">
                                     <li><a href=""><i class="fab fa-facebook-f"></i></a></li>
                                     <li><a href=""><i class="fab fa-twitter"></i></a></li>
                                     <li><a href=""><i class="fab fa-google-plus-g"></i></a></li>
                                     <li><a href=""><i class="fab fa-linkedin"></i></a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
             

              {%empty%}
             <!-- if no search result -->
             <h1 class="text-center text-danger">No results found</h1>
             {%endfor%}

             




        </div>
        {%endif%}
        <div class="col-3"></div>
    </div>
</div>


{%endblock%}